### ISSUE TITLE
[Core][♿] `:focus-visible` vs. `:focus`

### ISSUE THREAD

**Issue by mimshins** [sonnat/sonnat-ui#4]
Add a mechanism to differentiate the behavior of `:focus` and `:focus-visible`.

- `:focus`: Triggered when the user clicks or taps on an element or selects it with the keyboard’s `Tab` key.

- `:focus-visible`: Triggered by User-Agent on elements having `:focus` selector based on some heuristics that determine which one of the active elements should receive focus.
This selector is mostly useful to provide a different focus indicator based on the user’s input modality (mouse vs. keyboard).
For instance, let’s say you have `<a>` tag, you want to remove the focus outline when user focuses it via mouse but want to have retain an outline that goes in with the site theme when user focuses via keyboard.

Example:
```css
a:focus {
  outline: none;
}

a:focus-visible {
  outline: 3px solid currentColor;
}
```
